spring:
  application:
    name: one-line-a-day-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/onelineaday
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate # Use Flyway for schema updates
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true # For existing DBs

application:
  jwt:
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration: 86400000 # 1 day in ms
    refresh-expiration: 604800000 # 7 days in ms
